# Generated by Django 5.0.1 on 2024-03-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sowmya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sno', models.IntegerField(null=True)),
                ('BookingId', models.IntegerField(null=True)),
                ('PackageName', models.CharField(max_length=255)),
                ('From', models.DateField(null=True)),
                ('To', models.DateField(null=True)),
                ('Comment', models.CharField(max_length=255)),
                ('Status', models.CharField(max_length=255)),
                ('BookingDate', models.DateField(null=True)),
                ('Action', models.CharField(max_length=255)),
            ],
        ),
    ]
