# Generated by Django 5.0.1 on 2024-03-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tarak', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sowmya',
            old_name='Action',
            new_name='PackageLocation',
        ),
        migrations.RenameField(
            model_name='sowmya',
            old_name='Sno',
            new_name='Price',
        ),
        migrations.RemoveField(
            model_name='sowmya',
            name='BookingDate',
        ),
        migrations.RemoveField(
            model_name='sowmya',
            name='Status',
        ),
        migrations.AddField(
            model_name='sowmya',
            name='Package_type',
            field=models.CharField(choices=[('AllServices', 'AllServices'), ('FoodService', 'FoodService'), ('TravelService', 'TravelService'), ('Accomdation', 'Accomdation')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
