# Generated by Django 5.0.1 on 2024-03-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tarak', '0002_rename_action_sowmya_packagelocation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('Mobile_Number', models.IntegerField(null=True)),
                ('subject', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
