# Generated by Django 5.0.1 on 2024-03-30 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tarak', '0003_enquiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='username',
            new_name='name',
        ),
    ]
