# Generated by Django 5.0.1 on 2024-03-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tarak', '0004_rename_username_enquiry_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaisedTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Package_Name', models.CharField(max_length=255)),
                ('Package_Location', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=255)),
            ],
        ),
    ]
