# Generated by Django 5.0.1 on 2024-03-30 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tarak', '0005_raisedticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyBookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('PackageName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tarak.sowmya')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tarak.register')),
            ],
        ),
    ]
